version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: cine-mongo
    ports:
      - "27017:27017"          # optionnel (utile en debug)
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  cine-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: cine-api
    
    environment:      
      MONGO_URI: ${MONGO_URI:-mongodb+srv://vernierestephane:cinephoriapassword@cluster0.jdntgz0.mongodb.net/cinephoria?retryWrites=true&w=majority&appName=Cluster0}
      JWT_SECRET: ${JWT_SECRET:-cleSuperSecrete123456}
      PORT: 3000
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/films',res=>process.exit(res.statusCode===200?0:1))"]
      interval: 10s
      timeout: 3s
      retries: 5

  cine-front:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: cine-front
    ports:
      - "4200:80"
    restart: unless-stopped
    depends_on:
      cine-api:
        condition: service_healthy

  cine-mobile:
    build:
      context: ./cinephoria-mobile
      dockerfile: Dockerfile.mobile
    container_name: cine-mobile
    ports:
      - "8100:80"       
    restart: unless-stopped
    depends_on:
      cine-api:
        condition: service_healthy
    
volumes:
  mongo_data:
